add virtual alias trigger

diff --git a/rootfs/usr/local/bin/update_postgrey_whitelist b/rootfs/usr/local/bin/update_postgrey_whitelist
--- a/rootfs/usr/local/bin/update_postgrey_whitelist
+++ b/rootfs/usr/local/bin/update_postgrey_whitelist
@@ -3,18 +3,18 @@
 
 if [ "${ENABLE_POSTGREY}" = "true" ]; then
 
-  # Fail on error
-  set -e
+    # Fail on error
+    set -e
 
-  echo "Updating ${POSTGREY_SYSTEM_WHITELIST_FILE}..."
+    echo "Updating ${POSTGREY_SYSTEM_WHITELIST_FILE}..."
 
-  # Download latest file
-  curl --location --silent --output "/tmp/postgrey_whitelist_client.new" "${POSTGREY_WHITELIST_URL}"
-  
-  # Move downloaded file to final location
-  mv "/tmp/postgrey_whitelist_client.new" "${POSTGREY_SYSTEM_WHITELIST_FILE}"
+    # Download latest file
+    curl --location --silent --output "/tmp/postgrey_whitelist_client.new" "${POSTGREY_WHITELIST_URL}"
 
-  # Tell postgrey to reload the whitelist (if running)
-  pkill -HUP postgrey || true
+    # Move downloaded file to final location
+    mv "/tmp/postgrey_whitelist_client.new" "${POSTGREY_SYSTEM_WHITELIST_FILE}"
+
+    # Tell postgrey to reload the whitelist (if running)
+    pkill -HUP postgrey || true
 
 fi
